### ISSUE TITLE
HA 0.96

### ISSUE THREAD

**Issue by favarinbarracano** [Limych/media_player.linkplay#4]
Hi,
the component seems not working well with HA 0.96.
Any suggestions?
Thanks,

Manuel

**Comment by Limych** [comment]
Please, describe more information. Here is a template:


## Version of the custom_component
If you are not using the newest version, download and try that before opening an issue
If you are unsure about the version check the const.py file.

## Configuration

```yaml

Add your configs here.

```

## Describe the bug
A clear and concise description of what the bug is.


## Debug log

To enable debug logs check this https://www.home-assistant.io/components/logger/

```text

Add your logs here.

```
